spring.application.name=StudentManagmentSystem

# MySQL Connection
spring.datasource.url=jdbc:mysql://localhost:3306/studentManagementSystem
spring.datasource.username=root
spring.datasource.password=JOp97)#?6nmu
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
